name: cloud-api

version: '3.8'

services:
  api:
    image: ellencoutinho/api-clima:v2
    environment:
      - DB_USER=${DB_USER:-projeto}
      - DB_PASSWORD=${DB_PASSWORD:-projeto}
      - DB_HOST=${DB_HOST:-projeto}
      - DB_NAME=${DB_NAME:-projeto}
      - MINHA_SENHA=${MINHA_SENHA:-projeto}
    ports:
      - 8000:8000
    depends_on:
      - db  

  db:
    image: postgres:16
    ports:
      - 5430:5432
