name: cloud-api

version: '3.8'

services:
  api:
    build:
      context: ./app
    environment:
      - DB_USER=cloud
      - DB_PASSWORD=cloud
      - DB_HOST=db
      - DB_NAME=cloud
      - MINHA_VARIAVEL=${MINHA_SENHA:-projeto}
    ports:
      - 8000:8000
    depends_on:
      - db  

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cloud       
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: cloud
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
